### ISSUE TITLE
Grading of text/image answers

### ISSUE THREAD

**Issue by Feelx234** [cssh-rwth/autograde#12]
As we are not (yet) able to fully automatically grade textual answers of students we need a semi automatic solution.

After automatic tests have been run, it would be great to have a user interface that allows you to quickly grade students text submission by hand.

Minimal requirements are:
1. Show the answers that students gave (image or text)
2. Allow a grading person to specify comments and a grade
3. Write those back into e.g. the report but also somewhere else, such that if the archive gets overwritten by rerunning the tests, the comments and grades persist
4. allow the option to later revisit that comment and grade

Bonus requirements:
- Let a grader specify expected points to be mentioned ("Erwartungshorizont"), with possible grading schemes (e.g. 0.5 points for mentioning A, 0.5 points for mentioning B ...) or sth like mention at least 2 out of 4 each gives 0.5 point up to a max of 1. Also nice: feedback to students like: You forgot to mention A) -> - 0.5 points
- A way to check that all textual/image answers have been graded

A web interface would be great for that purpose. Preferably allow grading of all submissions for one task and then the next task rather than all tasks for one submission an then the next submission.

Possible issues:
- rendering rst into html?

**Comment by 0b11001111** [comment]
Except of the "Erwartungshorizont" all features are now included or am I missing something? For now, I'd like to keep that feature out as all the state is kept with the results archives and including an "Erwartungshorizont" in it would mean you leak all your grading criteria to the students which may not be a good idea sometimes. Providing graders with a separate list of such criteria shouldn't be a big deal in most cases though.

If that's not accurate feel free to re-open this issue ;)
