### ISSUE TITLE
Easy to use way to incorporate possible student complaints

### ISSUE THREAD

**Issue by Feelx234** [cssh-rwth/autograde#13]
As no automatic testing will be perfect, it would be great to have a unified way that allows you to easily, consistently and persistently update the grade of submissions.

**Comment by 0b11001111** [comment]
There's an interactive audit mode (`autograde audit --help`) being introduced in https://github.com/cssh-rwth/autograde/tree/refactor-workflow.

**Comment by 0b11001111** [comment]
By now, audit mode is not just some ad hoc feature but a central element for scenarios where code cannot be tested fully automatically. I'll propose a guide to map common grading workflows with autograde, see #19.
