### ISSUE TITLE
Moodle integration

### ISSUE THREAD

**Issue by Feelx234** [cssh-rwth/autograde#14]
The current state is, that the after all grading is finished we have to notify students of their grades and the reasons for that grade.

I wrote a small selenium script that gets the job done, but it might be worth exploring the API of moodle directly.

**Comment by 0b11001111** [comment]
In discussion with @flemmerich we agreed on keeping this feature separate of _autograde_. I suggest to create a repository in RWTH's gitlab instance with one python/bash script for downloading submissions and another to update grades.
