### ISSUE TITLE
More information in summary

### ISSUE THREAD

**Issue by Feelx234** [cssh-rwth/autograde#15]
It would be great if the summary.csv also contains the grade per task, it currently only shows the total grade.

I have already made that change PR coming.

**Comment by 0b11001111** [comment]
The `summary.csv` is actually used? I thought about to discard it as it is completely redundant to the json file but with less information...

**Comment by Feelx234** [comment]
I am talking about the summary.csv that gets produced by `autograde summary`. In my version of autograde there is no `.json` equivalent, and csv is easy to read into a dataframe.

**Comment by 0b11001111** [comment]
Ah, I confused that with `test_results.csv` :D

**Comment by 0b11001111** [comment]
As of c75fc4ec2d82de809d12cbbe43b8d3bd6279cab3 raw data is exported as well. For more custom reports this should be sufficient and one has not to dig out data manually from archives. Also, this keeps `summary.csv` more consistent.
