### ISSUE TITLE
Current version not working

### ISSUE THREAD

**Issue by lukasmoldon** [cssh-rwth/autograde#20]
The current version of autograde is not working for me on Python 3.8.5:

![error](https://user-images.githubusercontent.com/49486044/99719379-82ac3f00-2aac-11eb-837d-416e182b161b.JPG)

However, I checked out at commit 470d3b4bc0e4584e5fb0fa628dbe2fe35156cd6a and it is working fine.

I also noticed (as minor issue - but maybe it is even intended?) that the --target directory for results is not initialized automatically:

![error2](https://user-images.githubusercontent.com/49486044/99720157-a02dd880-2aad-11eb-8c65-41c201587606.JPG)

**Comment by 0b11001111** [comment]
I'll investigate the first issue. The latter one just follows common practice I did not want to break with (like `open('/some/path/to/file.txt', mode='wt')` fails if the directory `path` does not exist for instance).
