### ISSUE TITLE
subprocess.call VS subprocess.run in autograde/cli/test.py

### ISSUE THREAD

**Issue by Feelx234** [cssh-rwth/autograde#21]
In autograde/cli/test.py the subprocess is executed once using.call (no backend) and once using.run (with backend)

.call works fine
But when using.run with backend podman I get an error on Ubuntu complaining about the ``:Z`` argument not being recognized by podman. I think is related to the thing that the arguments are already surrounded with `"` which are then passed into .run

backend=podman works fine if I just replace line 68 with line 66 and remove the `:Z`

**Comment by 0b11001111** [comment]
The container backends have been fully re-factored in c6f093bc1d83c60bfbdd7e878e83dedd6d6d4a2a. Not sure if this has resolved in the meantime. Just re-open if this has not been the case.
