### ISSUE TITLE
Filename of archive in summary.csv

### ISSUE THREAD

**Issue by Feelx234** [cssh-rwth/autograde#22]
It would be great if the filename of the archive is included in the summary.csv. This makes it much easier to identify which archive belongs to which student. Otherwise one has to search through all the archives to find the matching one. 
I have already implemented that in a fork of mine: https://github.com/Feelx234/autograde
This fork also includes some other changes which makes it unsuitable for a direkt PR.

**Comment by 0b11001111** [comment]
This one should be easy to implement. I'll cover that soonish

**Comment by 0b11001111** [comment]
Fixed in 2406aa8bd9d154147b21686c301645dfd84266c7
